# Generated by Django 4.1.5 on 2024-08-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0002_alter_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.FileField(upload_to='Certificate/'),
        ),
    ]
