# Generated by Django 4.1.5 on 2025-02-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='position',
            field=models.TextField(default='Uninon', max_length=255),
            preserve_default=False,
        ),
    ]
