# Generated by Django 4.1.5 on 2024-08-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
