# Generated by Django 4.1.5 on 2024-08-24 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0003_alter_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
