# Generated by Django 4.1.5 on 2024-08-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='typeof',
            field=models.CharField(max_length=30),
        ),
    ]
